name: CICD

on:
  push:
    branches: ["main"]
  pull_request:

jobs:

  ci:
    name: Build & Test Java App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'

      # User mvnw because automatically download and run maven with that guaranteed version.
      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Build (using Maven Wrapper)
        run: ./mvnw -B -V clean package

      - name: Run tests (using Maven Wrapper)
        run: ./mvnw -B test
      
      - name: Publish JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: springboot-jar
          path: target/*.jar
  
  cd:
    name: Deploy to GKE
    needs: ci
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    env:
      IMAGE: us-central1-docker.pkg.dev/amazing-gearing-480202-f2/portfolio-apps/java-app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: springboot-jar
      
      - name: Generate version tag
        id: version
        run: |
          # Short commit SHA (first 7 chars) + current date
          SHORT_SHA=$(git rev-parse --short HEAD)
          # Change the prefix below to whatever you like
          VERSION="dev-${SHORT_SHA}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          create_credentials_file: true
          workload_identity_provider: 'projects/988278378910/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: 'github-actions@amazing-gearing-480202-f2.iam.gserviceaccount.com'
      
      - name: Docker login to GAR
        run: gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

      - name: Build & Push Docker image
        run: |         
          docker build . -t ${{ env.IMAGE }}:${{ steps.version.outputs.version }} -t ${{ env.IMAGE }}:latest
          docker push ${{ env.IMAGE }}:${{ steps.version.outputs.version }}
          docker push ${{ env.IMAGE }}:latest